In [1]:
import numpy as np
import nrrd

In [3]:
readdata, header = nrrd.read('/Users/baymac/Documents/Kaggle/imageData/resampled/train/00000/FLAIR.nrrd')
print(readdata.)

[[[0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  ...
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]]

 [[0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  ...
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]]

 [[0.02778567 0.02778567 0.02778567 ... 0.02778567 0.02778567 0.02778567]
  [0.02778567 0.027785